MKSHELL=$PLAN9/bin/rc

<$PLAN9/src/mkhdr

TARG=cursel backingscale expandclasses  zk printmonth

<$PLAN9/src/mkmany

CLEANFILES=$CLEANFILES *.native

o.zk: zk.o
	$LD $LDFLAGS -L/usr/local/lib -lzookeeper_mt -o $target zk.o

$O.backingscale: backingscale-objc.o
	$LD -o $target $prereq

%-objc.$O: %.m
	$CC $CFLAGS -o $target $stem.m

$O.%:	%.sml
	mlton -output $target $stem.mlb

$O.%: 	%.ml
	corebuild -no-hygiene $stem.native
	cp $stem.native $target

reallyclean:V: clean
	/bin/rm -rf _build .cm

install:V:
	cp o.expandclasses /Users/marius/bin/darwin/x86_64/pants/expandclasses
